#Local LLM quota counters
#Fri May 29 17:56:56 CEST 2026
ai.koog.prompt.llm.GoogleLLMProvider_4e67cfe1.gemini-2.5-flash-lite.count=1
ai.koog.prompt.llm.GoogleLLMProvider_4e67cfe1.gemini-2.5-flash-lite.date=2026-05-28
ai.koog.prompt.llm.GoogleLLMProvider_65036e8d.gemini-2.0-flash-lite.count=1
ai.koog.prompt.llm.GoogleLLMProvider_65036e8d.gemini-2.0-flash-lite.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_112c2930.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_112c2930.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_128ffb3f.llama-3.3-70b-versatile.count=1
ai.koog.prompt.llm.OpenAILLMProvider_128ffb3f.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_19cdc217.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_19cdc217.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_25ce435.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_25ce435.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_266da047.llama-3.3-70b-versatile.count=1
ai.koog.prompt.llm.OpenAILLMProvider_266da047.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_28554ac8.openai_gpt-oss-120b.count=9
ai.koog.prompt.llm.OpenAILLMProvider_28554ac8.openai_gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_2a99ca99.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_2a99ca99.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_2abc55c4.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_2abc55c4.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_2c8a445b.llama-3.3-70b-versatile.count=1
ai.koog.prompt.llm.OpenAILLMProvider_2c8a445b.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_314b7945.openai_gpt-oss-120b.count=8
ai.koog.prompt.llm.OpenAILLMProvider_314b7945.openai_gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_394fb736.openai_gpt-oss-120b.count=3
ai.koog.prompt.llm.OpenAILLMProvider_394fb736.openai_gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_45984654.openai_gpt-oss-120b.count=2
ai.koog.prompt.llm.OpenAILLMProvider_45984654.openai_gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_47fb7ec9.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_47fb7ec9.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_52bba91a.llama-3.3-70b-versatile.count=7
ai.koog.prompt.llm.OpenAILLMProvider_52bba91a.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_52f9e8bb.llama-3.3-70b-versatile.count=16
ai.koog.prompt.llm.OpenAILLMProvider_52f9e8bb.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_539316bb.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_539316bb.llama-3.3-70b-versatile.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_5a7b6b75.llama-3.3-70b-versatile.count=1
ai.koog.prompt.llm.OpenAILLMProvider_5a7b6b75.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_66b0e207.openai_gpt-oss-120b.count=2
ai.koog.prompt.llm.OpenAILLMProvider_66b0e207.openai_gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_6d7b001b.llama-3.3-70b-versatile.count=7
ai.koog.prompt.llm.OpenAILLMProvider_6d7b001b.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_6d874695.llama-3.3-70b-versatile.count=2
ai.koog.prompt.llm.OpenAILLMProvider_6d874695.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_6fe04f2a.llama-3.3-70b-versatile.count=17
ai.koog.prompt.llm.OpenAILLMProvider_6fe04f2a.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_733534f9.llama-3.3-70b-versatile.count=3
ai.koog.prompt.llm.OpenAILLMProvider_733534f9.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_74a58a06.openai_gpt-oss-120b.count=12
ai.koog.prompt.llm.OpenAILLMProvider_74a58a06.openai_gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_795f6681.llama-3.3-70b-versatile.count=4
ai.koog.prompt.llm.OpenAILLMProvider_795f6681.llama-3.3-70b-versatile.date=2026-05-28
ai.koog.prompt.llm.OpenAILLMProvider_e01a26b.gpt-oss-120b.count=1
ai.koog.prompt.llm.OpenAILLMProvider_e01a26b.gpt-oss-120b.date=2026-05-29
ai.koog.prompt.llm.OpenAILLMProvider_e01a26b.openai_gpt-oss-120b.count=5
ai.koog.prompt.llm.OpenAILLMProvider_e01a26b.openai_gpt-oss-120b.date=2026-05-29
